### ISSUE TITLE
Marvell 88F6560 uboot.bin help pls

### ISSUE THREAD

**Issue by ilkeroz17** [msdos03/avanta-uboot-f660#1]
hi friend,

aruba ap-135 spi uboot.bin i need compilation. later openwrt install 

CPU1: Marvell 88F6560 (1.6 GHz)
FLA1: 16 MiB (Macronix MX25L12845EMI-10G)
RAM1: 256 MiB (Micron MT41J128M8JP-15E × 2)

help pls very nice hardware openwrt install plss

please answer me please

**Comment by msdos03** [comment]
> hi friend,
> 
> aruba ap-135 spi uboot.bin i need compilation. later openwrt install
> 
> CPU1: Marvell 88F6560 (1.6 GHz) FLA1: 16 MiB (Macronix MX25L12845EMI-10G) RAM1: 256 MiB (Micron MT41J128M8JP-15E × 2)
> 
> help pls very nice hardware openwrt install plss
> 
> please answer me please

I'd like to help but it's really hard to do that without a test device.

**Comment by ilkeroz17** [comment]
> > hi friend,
> > aruba ap-135 spi uboot.bin i need compilation. later openwrt install
> > CPU1: Marvell 88F6560 (1.6 GHz) FLA1: 16 MiB (Macronix MX25L12845EMI-10G) RAM1: 256 MiB (Micron MT41J128M8JP-15E × 2)
> > help pls very nice hardware openwrt install plss
> > please answer me please
> 
> I'd like to help but it's really hard to do that without a test device.

First of all, thank you very much for your reply.  I will try to help you technically, please let's try. yes it's hard but i want to try. Please support me and let's solve this together. Let's support recycling. We can recover thousands of devices all over the world. 
![WhatsApp Image 2022-12-01 at 13 25 13](https://user-images.githubusercontent.com/110835938/205029967-27764711-656a-4cc8-ab6b-f751e7c75950.jpeg)
![WhatsApp Image 2022-12-01 at 13 25 12](https://user-images.githubusercontent.com/110835938/205030022-cef1b6cf-c820-4ab9-a878-38f726287c02.jpeg)

**Comment by msdos03** [comment]
> > > hi friend,
> > > aruba ap-135 spi uboot.bin i need compilation. later openwrt install
> > > CPU1: Marvell 88F6560 (1.6 GHz) FLA1: 16 MiB (Macronix MX25L12845EMI-10G) RAM1: 256 MiB (Micron MT41J128M8JP-15E × 2)
> > > help pls very nice hardware openwrt install plss
> > > please answer me please
> > 
> > 
> > I'd like to help but it's really hard to do that without a test device.
> 
> First of all, thank you very much for your reply. I will try to help you technically, please let's try. yes it's hard but i want to try. Please support me and let's solve this together. Let's support recycling. We can recover thousands of devices all over the world. ![WhatsApp Image 2022-12-01 at 13 25 13](https://user-images.githubusercontent.com/110835938/205029967-27764711-656a-4cc8-ab6b-f751e7c75950.jpeg) ![WhatsApp Image 2022-12-01 at 13 25 12](https://user-images.githubusercontent.com/110835938/205030022-cef1b6cf-c820-4ab9-a878-38f726287c02.jpeg)

I have other devices to deal with. And I am very busy studying in school. I have no reason to do these time-consuming things. My repos are all public, everyone can use it under GPL lisence. So please do it yourself and enjoy the sense of achievement.
