### ISSUE TITLE
F660内存升级为256M，Uboot只能识别到128M。

### ISSUE THREAD

**Issue by xiaole51** [msdos03/avanta-uboot-f660#2]
Hi~大佬我又来提问了
F660内存升级为256M，Uboot只能识别到128M。
看来内存容量是Uboot中指定的，源码中如何修改才能别到256M呢？
Openwrt中也需要修改吧？OP教程多已经找到位置了。

一下是升级内存后的Uboot信息：
Board: F660
SoC: 88F6560 A0
CPU: Marvell Feroceon (Rev 1) - LE
CPU @ 0Mhz, L2 @ 0Mhz
DDR3 @ 0Mhz, TClock @ 200Mhz
PEX 0: Detected No Link.
PEX 1: Root Complex Interface, Detected Link X1
DRAM: 128 MB
CS 0: base 0x00000000 size 128 MB
Addresses 10M - 0M are saved for the U-Boot usage.
NAND: 1bit HM ECC, Size: 32 MiB
* Warning - bad CRC or NAND, using default environment

**Comment by msdos03** [comment]
首先提醒一下，经过实验证明，nand闪存升级不了，我也找不出解决方案。
但是ram还真没准可以升级。
决定ram大小的只有dramregs_xxx.txt了
这个东西是我从原版拷贝出来的，我也搞不大明白。不过我参考uboot里的一些说明建议你可以试试
把dramregs_f660_128m_ddr3.txt里面的`0xFFD01504 0x07FFFFF1`这行改成
`0xFFD01504 0x0FFFFFF1`
如果还不行，再尝试修改0xffd01410这个地址，改成`0xFFD01410 0x040000DD`或者其他的文件内这个地址的值
(u-boot主线内部搜索文件kwbimage.cfg即可看到这类文件)
(如果上面的就能成功就不要动这个地址了，毕竟我不保证这个地址修改内容的正确性)

**Comment by xiaole51** [comment]
不好意思，今天才看到大佬的恢复。
测试后结果如下：
1.修改dramregs_f660_128m_ddr3.txt文件中的0xFFD01504 0x0FFFFFF1。
在uboot中成功识别256M内存，进入系统也是256M，但是启动系统后10秒左右内核崩溃重启。 （已能打开web页面，ssh可连接。）
2.继续修改0xFFD01410 0x040000DD后编译，上面现象没发生变化。
3.不换固件，重刷128M的Uboot,一切正常。
4.难道是我编译Openwrt修改内存大小有误？
/openwrt-avanta/target/linux/avanta/files/arch/arm/boot/dts/avanta-f460-f660.dts文件中修改reg = <0x00000000 0x8000000>;。0x8000000改为0x10000000


256M Uboot启动信息：
Board: F660
SoC:   88F6560 A0
CPU:   Marvell Feroceon (Rev 1) - LE
       CPU @ 0Mhz, L2 @ 0Mhz
       DDR3 @ 0Mhz, TClock @ 200Mhz
PEX 0: Detected No Link.
PEX 1: Root Complex Interface, Detected Link X1
DRAM:  256 MB
       CS 0: base 0x00000000 size 256 MB
       Addresses 10M - 0M are saved for the U-Boot usage.
NAND:  1bit HM ECC, Size: 32 MiB
*** Warning - bad CRC or NAND, using default environment

内核崩溃重启：
[  168.986850] 7fc0: b6b04e70 b6a48ec0 b6f36658 0000007d b6f37460 b6f36658 00000000 bee50ecc
[  168.995072] 7fe0: b6a49000 bee50c40 b6f1e0b0 b6f1e16c
[  169.000157] Code: e1a07000 e1a08001 e24dd028 0a000042 (e5943004) 
[  169.006327] ---[ end trace 13cf2b659a7ffd0f ]---
[  169.010987] Kernel panic - not syncing: Fatal exception
[  169.016245] Rebooting in 3 seconds..

**Comment by msdos03** [comment]
@xiaole51 我觉得应该在uboot下测试一下128m以上dram的可用性。具体方法是找一个128m以上，256m以下的地址，在uboot命令行用mw命令随便写点数据进去，之后用md命令读取这块数据。如果之前写入的数据正确，那么这段内存就是可用的，可能是内核配置有问题。

不管怎样，你可以试试改用dramregs_533_512m_ddr3.txt把
0xFFD01504 0x1FFFFFF1改成
0xFFD01504 0x0FFFFFF1
或者直接用dramregs_533db_kw2_ddr3.txt
或dramregs_533rd_kw2_ddr3.txt试试看

另外，你给的traceback好像不全啊，没啥有用信息。

**Comment by xiaole51** [comment]
经过一天的折腾，应该是成功了。 
也是参考了其他dramregs文件信息，试到dramregs_533db_kw2_ddr3.txt内的参数后正常了。
Uboot及系统均识别256M内存，运行一个多小时没崩溃，具体修改内容如下：
0xFFD01504 0x07FFFFF1   -> 0xFFD01504 0x0FFFFFF1
0xFFD01410 0x0400000D -> 0xFFD01410 0x040000CC

![image](https://github.com/msdos03/avanta-uboot-f660/assets/22991235/1c556d42-3e0a-4843-8372-c8c582c4f1fb)

可以完美收官了。
感谢大佬手把手指导。

**Comment by msdos03** [comment]
@xiaole51 
那么，我就把你实验出的dramregs加到源码里面了，方便其他人使用

**Comment by xiaole51** [comment]
> @xiaole51 
> 那么，我就把你实验出的dramregs加到源码里面了，方便其他人使用

当然可以，很高兴能给项目出了微薄之力。

**Comment by msdos03** [comment]
@xiaole51 想问问你当年升级用的颗粒是什么型号？不知还记得不

**Comment by msdos03** [comment]
@xiaole51 我尝试用nt5cb128m16ip-ek升级，但是无限循环bootrom信息，把原先的芯片焊回去又好了

**Comment by xiaole51** [comment]
这是我当年升级内存的笔记，请参考。


CPU：Marvell 88f6560
支持16 bit的DDR2接口和DDR3接口

内存规格：H5TQ1G63DFR-h9C Hynix 1Gb DDR3 64M x 16 96ball FBGA(x16）DDR3-1333 9-9-9
C = 64M x 16 (实际容量许除以8)
h9 = DDR3-1333 9-9-9

闪存：HY27US08561A （32Mx8bit）VCC = 2.7 to 3.6V 48TSOP1

内存替换原则
原机内存是 DDR3-1333 128M 16位，BGA96球颗粒。可以用更大容量的ddr3 16位颗粒升级。

颗粒选择方法：内存类型，位宽，封装脚位数量，这三个参数对上基本就能用。

如果主板上有两个内存颗粒，就是8位的，单颗是16位的。

电脑内存双面的均为8位颗粒。 单面的有可能是16位的。

闪存替换原则

封装规格脚位相同

电压相同，一般分3.3v和1.8v

Openwrt 内存容量修改方法：

源码中的~/openwrt-avanta/target/linux/avanta/files/arch/arm/boot/dts/avanta-f460-f660.dts文件中修改。0x8000000改为0x10000000
memory {
device_type = "memory";
reg = <0x00000000 0x8000000>;
};

内存容量值对照表
reg = <0x0 0x20000000>; // 512MB RAM
reg = <0x0 0x10000000>; // 256MB RAM
reg = <0x0 0x8000000>; // 128MB RAM
reg = <0x0 0x4000000>; // 64MB RAM

修改后重新编译得到对应版本的固件。

Uboot内存容量修改（修改后可识别256M内存）
编辑/home/gonggy/avanta-uboot-f660/dramregs_f660_128m_ddr3.txt文件内容
0xFFD01504 0x07FFFFF1 -> 0xFFD01504 0x0FFFFFF1
0xFFD01410 0x0400000D -> 0xFFD01410 0x040000CC

**Comment by msdos03** [comment]
@xiaole51 谢谢回复，我研究了半天，只发现一个可能就是我换的DDR3 16位颗粒太新了，不支持CL5。我其实是想确切知道哪个型号的颗粒绝对兼容，所以才来问的
