### ISSUE TITLE
BootROM: Bad header at offset

### ISSUE THREAD

**Issue by catzy007** [msdos03/avanta-uboot-f660#3]
Hi, i currently installing uboot by following your tutorial in your [OpenWRT forum post](https://forum.openwrt.org/t/openwrt-now-support-zte-f660-v3-0-and-hgg420n/101136).

* Method1 is not working for me because my device does not have dd preinstalled
* Method2 resulted in a bunch of `BootROM: Bad header at offset` error
* Method3 resulted in working uboot but after following step 2,3 in method2 i get `BootROM: Bad header at offset` error.

My device is ZXA10 F660 V3. I'm using version `Stable_v1.4`, file `u-boot-f660_f660_128m_ddr3_nand.bin` from this repository. Is there any way to resolve this? 

Please let me know and thank you for your great work! I wish you would upstream your work to OpenWRT main repo one day.

[UPDATE] I also try version 1.0 which doesn't show any error but it kept repeating `Booting from NAND flash` instead of getting into proper marvell uboot.

**Comment by msdos03** [comment]
That's very strange. 
Please verify the md5 sum of your download to see if it's broken. 
Can you post what commands you run in uboot and the output?
This openwrt runs on an linux kernel with some simple but dirty hacks, I don't think openwrt will accept this. But I will continue maintaining it and sync with latest openwrt changes.

**Comment by catzy007** [comment]
This is uboot md5sum.
```
991d746a8253e88f628d49a2eb0dda17  uboot.bin
```

And after installing it to the device.
```
=> tftp uboot.bin
Using egiga0 device
TFTP from server 192.168.1.100; our IP address is 192.168.1.1
Filename 'uboot.bin'.
Load address: 0x2000000
Loading: ##############################################
done
Bytes transferred = 671320 (a3e58 hex)
=> nand erase

Skipping bad block at  0x03d60000                                          
Erasing at 0x7fe0000 -- 100% complete.

=> nand write 0x2000000 0x0 0x100000
NAND write: '0x100000' is not a number
=> nand write 0x2000000 0x0 0x100000
NAND write: 1048576 bytes
=>
```

This is what comes out (and a buch more).
```
BootROM 1.34
Booting from NAND flash
BootROM: Bad header at offset 00000000
BootROM: Bad header at offset 00010000
BootROM: Bad header at offset 00020000
BootROM: Bad header at offset 00030000
BootROM: Bad header at offset 00040000
BootROM: Bad header at offset 00050000
BootROM: Bad header at offset 00060000
BootROM: Bad header at offset 00070000
BootROM: Bad header at offset 00080000
BootROM: Bad header at offset 00090000
BootROM: Bad header at offset 000A0000
BootROM: Bad header at offset 000B0000
BootROM: Bad header at offset 000C0000
BootROM: Bad header at offset 000D0000
BootROM: Bad header at offset 000E0000
BootROM: Bad header at offset 000F0000
BootROM: Bad header at offset 00100000
BootROM: Bad header at offset 00110000
BootROM: Bad header at offset 00120000
BootROM: Bad header at offset 00130000
BootROM: Bad header at offset 00140000
BootROM: Bad header at offset 00150000
BootROM: Bad header at offset 00160000
BootROM: Bad header at offset 00170000
```

But if i'm using kwboot, here is roughly what comes out.
```
 __   __                      _ _
|  \/  | __ _ _ ____   _____| | |
| |\/| |/ _` | '__\ \ / / _ \ | |
| |  | | (_| | |   \ V /  __/ | |
|_|  |_|\__,_|_|    \_/ \___|_|_|
         _   _     ____              _
        | | | |   | __ )  ___   ___ | |_ 
        | | | |___|  _ \ / _ \ / _ \| __| 
        | |_| |___| |_) | (_) | (_) | |_ 
         \___/    |____/ \___/ \___/ \__| 
 ** LOADER **


U-Boot 2009.08 (11月 19 2022 - 15:53:08) Marvell version: 2.1.6_NQ

Board: F660
SoC:   88F6560 A0
CPU:   Marvell Feroceon (Rev 1) - LE
       CPU @ 0Mhz, L2 @ 0Mhz
       DDR3 @ 0Mhz, TClock @ 200Mhz
PEX 0: Detected No Link.
PEX 1: Root Complex Interface, Detected Link X1
DRAM:  128 MB
       CS 0: base 0x00000000 size 128 MB
       Addresses 10M - 0M are saved for the U-Boot usage.
NAND:  1bit HM ECC, Size: 128 MiB
*** Warning - bad CRC or NAND, using default environment

USB 0: Host Mode
Shutting down unused interfaces:
       SATA
Modules Detected:
       GPON module detected.
       TDM module.
       Ethernet Switch on MAC0.
       3xFE PHY Module.
       GE-PHY on Switch port #0.
Net:   egiga0 [PRIME], egiga1
Hit any key to stop autoboot:  0 

NAND read: device 0 offset 0x100000, size 0x300000
 3145728 bytes read: OK
## Booting kernel from Legacy Image at 02000000 ...
   Image Name:   ARM OpenWrt Linux-5.15.114
   Created:      2023-06-03   8:27:00 UTC
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    2808587 Bytes =  2.7 MB
   Load Address: 00008000
   Entry Point:  00008000
   Verifying Checksum ... OK
   Loading Kernel Image ... OK
OK
```

**Comment by msdos03** [comment]
I know, your f660 have 128m nand flash. But I have seen only f660 with 32m nand flash. That's the problem. I will make an option to build uboot for large page nand when I have time. And openwrt need change for this new nand flash size too.
For reference, I need you to post an HD photo of the nand flash on your f660.

**Comment by catzy007** [comment]
That make so much sense, the flash chip in my device is `SPANSION S34ML01G100TF100` i'm sorry i cannot provide a proper picture because a glued antenna cable in way.
![IMG_20230619_201545_634](https://github.com/msdos03/avanta-uboot-f660/assets/38147269/fba7436b-3858-456a-ab2f-05914c1887b7)

But anyway take your time and thank you for your great work and reply!

**Comment by msdos03** [comment]
@catzy007 Your board is kind of special, so I still want the pictures of both sides of the board to see the configuration resistors. That's a useful reference for upgrading nand flash. Thanks!

**Comment by catzy007** [comment]
You can see resized version of my board in https://openwrt.org/toh/zte/zxa10f660#photos Ii will add full res later.

**Comment by catzy007** [comment]
Here is the full res version. I hope this helps!

https://catzy007.github.io/things/f660v3/board-top-HQ.jpg
https://catzy007.github.io/things/f660v3/board-bottom-HQ.jpg

**Comment by msdos03** [comment]
[u-boot-f660_f660_128m_ddr3_nand.zip](https://github.com/msdos03/avanta-uboot-f660/files/11854368/u-boot-f660_f660_128m_ddr3_nand.zip)
@catzy007  Try this one, and tell me if it works.

**Comment by catzy007** [comment]
Can confirm that it works! Thank you.
```
BootROM 1.34
Booting from NAND flash
BootROM: Image checksum verification PASSED

 __   __                      _ _
|  \/  | __ _ _ ____   _____| | |
| |\/| |/ _` | '__\ \ / / _ \ | |
| |  | | (_| | |   \ V /  __/ | |
|_|  |_|\__,_|_|    \_/ \___|_|_|
         _   _     ____              _
        | | | |   | __ )  ___   ___ | |_ 
        | | | |___|  _ \ / _ \ / _ \| __| 
        | |_| |___| |_) | (_) | (_) | |_ 
         \___/    |____/ \___/ \___/ \__| 
 ** LOADER **


U-Boot 2009.08 ( 6月 24 2023 - 11:24:35) Marvell version: 2.1.6_NQ

Board: F660
SoC:   88F6560 A0
CPU:   Marvell Feroceon (Rev 1) - LE
       CPU @ 0Mhz, L2 @ 0Mhz
       DDR3 @ 0Mhz, TClock @ 200Mhz
PEX 0: Detected No Link.
PEX 1: Root Complex Interface, Detected Link X1
DRAM:  128 MB
       CS 0: base 0x00000000 size 128 MB
       Addresses 10M - 0M are saved for the U-Boot usage.
NAND:  1bit HM ECC, Size: 128 MiB
*** Warning - bad CRC or NAND, using default environment

USB 0: Host Mode
Shutting down unused interfaces:
       SATA
Modules Detected:
       GPON module detected.
       TDM module.
       Ethernet Switch on MAC0.
       3xFE PHY Module.
       GE-PHY on Switch port #0.
Net:   egiga0 [PRIME], egiga1
Hit any key to stop autoboot:  0 
Marvell>>
```

**Comment by msdos03** [comment]
@catzy007 also try this one to make sure my new build scripts have no problem.
[u-boot_new_build_system.zip](https://github.com/msdos03/avanta-uboot-f660/files/11854555/u-boot_new_build_system.zip)

**Comment by catzy007** [comment]
Unfortunately the new build system resulted the following instead of a proper marvell uboot.
```
BootROM 1.34
Booting from NAND flash

BootROM 1.34
Booting from NAND flash

BootROM 1.34
Booting from NAND flash

BootROM 1.34
Booting from NAND flash

BootROM 1.34
Booting from NAND flash

BootROM 1.34
Booting from NAND flash

BootROM 1.34
Booting from NAND flash
```

**Comment by msdos03** [comment]
@catzy007 Please try again. I compared above two binaries and found no differences except a build time info and the crc32 checksum. I think that won't cause any problem.
If it still like this, try again the previous working binary. I worry if your hardware have problems.

**Comment by catzy007** [comment]
After trying few things i can confirm that it is working! `U-Boot 2009.08 ( 6月 24 2023 - 12:46:23) Marvell version: 2.1.6_NQ` I forget to wipe the entire nand before installing uboot. Thank you!
