### ISSUE TITLE
I need your help to get U-Boot running on ZTE F6600P

### ISSUE THREAD

**Issue by acassis** [msdos03/avanta-uboot-f660#4]
Hi msdos03,
I found your project thanks to your post at https://forum.openwrt.org/t/openwrt-now-support-zte-f660-v3-0-and-hgg420n/101136

I downloaded the u-boot-f660_f660_128m_ddr3_nand.bin put it on my tftp server, used the original u-boot bootloader from F6600P to load this binary at RAM position 0x0 and ran "go 0x0". It failed after printing some initialization message (NAND, RAM, etc, detected).

So, I think it is crashing at some late point, but since I don't have JTAG support for chip used on this router, I don't know where it is stopping. Could you please help me?

**Comment by msdos03** [comment]
This is the first time I hear about zte f6600p, I don't know what SoC it has and other hardware details. I'm suprised that my u-boot for f660 can run on your hardware, even though it crashed. I need to know more about your hardware.

**Comment by acassis** [comment]
It uses a ZX279128S chip, I put the complete boot message from original firmware here:
https://acassis.wordpress.com/2024/02/26/zte-f6600p-boot-log/

More info:
https://www.zte.com.cn/global/product_index/smart_home_en/ont/zxhn-f6600p/zxhn-f6600p.html

I think it is a new version of F660 and not to easy to find to buy, but it is available at Alibaba: https://www.alibaba.com/product-detail/ZXHN-F6600P-AX3000-dual-band-Wifi6-1600721708999.html

**Comment by msdos03** [comment]
That's a different SoC, not supported by my project. And what's more, no uboot source code or kernel source code is available for this SoC.

**Comment by acassis** [comment]
whoa! Thank you @msdos03 so ZTE is not compliant with the GPL license right?

**Comment by msdos03** [comment]
> whoa! Thank you @msdos03 so ZTE is not compliant with the GPL license right?

No, it isn't. ZXIC SoCs have no leaked SDK. It is a very bad chip company.
